### PR TITLE
add Instagram.shareAsset feature

### PR DESCRIPTION
**Pull request by sky-code**
based on this article http://blog.horizon.camera/post/102273431070/video-share-objc-ios-instagram feature for sharing video to instagram on ios

### CODE REVIEW

**Comment by vstirbu** [comment]
Thanks for the PR!

Can you share an example of the asset url? It might be possible to keep the JavaScript API simpler by adding the option to share the asset url with the current `share` method.

**Comment by sky-code** [comment]
sorry I can't, I hope someone can catch this "asset url" by using UISaveVideoAtPathToSavedPhotosAlbum in debug break point variables inspector

**Comment by sky-code** [comment]
Hello there, please read this http://stackoverflow.com/questions/34226433/instagram-hooks-pre-select-media-issue 
If anyone can update code to work with new method based on instagram://library?LocalIdentifier=\(localID) url, please help with it.
Add this code http://stackoverflow.com/a/36019299 for converting urls, change url parameter "AssetPath" to new "LocalIdentifier" and this must work

**Comment by sky-code** [comment]
Hello again, I update code and test it, everything is working well, based on PHAsset LocalIdentifier

**Comment by vstirbu** [comment]
Thanks for updating the PR.

The question now is that if this adds a new method we could separate the canvas case from the other cases in which the input is an URL, and make the new method work for both iOS and Android. Each case would be handled based on the URI scheme.

**Comment by sky-code** [comment]
This new method work for both image and video, only if you have PHAsset LocalIdentifier and only in iOS 8+, also this feature **undocumented**, because of that I don't see any reason for 

> separate the canvas case

and 

> make the new method work for both iOS and Android

Just add as new method, because in any moment Instagram can change behaviour for this feature

**Pull request merged**
