### PR TITLE
kludge to fix null pointer on low memory devices

### PR DESCRIPTION
**Pull request by rodrigograca31**

### CODE REVIEW

**Comment by rodrigograca31** [comment]
this fixes #72

**Comment by rodrigograca31** [comment]
also not sure if npm will automatically pick up this changes.......? otherwise don't forget to publish to npm....

**Comment by vstirbu** [comment]
also published 🚀

**Comment by rodrigograca31** [comment]
YAY! Thanks! :confetti_ball: :tada: :confetti_ball: 

(So you have to manually publish to npm right? I thought they would automatically update nowadays....)

**Pull request merged**
