### PR TITLE
Fix sharing on iOS

### PR DESCRIPTION
**Pull request by LucWollants**
### Fixed
- Fixed sharing to iOS. Changed file extension to `ig` and change UTI to `com.instagram.photo`.

### CODE REVIEW

**Comment by jk90-obi** [comment]
This works, can we have someone with write access to the repo to review & approve PR?

**Comment by roxteddy** [comment]
So the igo extension is not registered by Instagram on iOS anymore ?

**Comment by LucWollants** [comment]
If `igo` is used Instragram is no longer shown on the Share Sheet.

**Comment by rodrigograca31** [comment]
@LucWollants
question: doesnt this break for older iOS versions? 

or actually for older Instagram versions? meaning seems Intagram changed their "package id" and only those who updated Instagram will have the new "package id"

**Comment by LucWollants** [comment]
> question: doesnt this break for older iOS versions?
> 
> or actually for older Instagram versions? meaning seems Intagram changed their "package id" and only those who updated Instagram will have the new "package id"

I did not test this, shame on me. But if that would be the case it makes sense to make this configurable?

**Comment by rodrigograca31** [comment]
I wouldn't say configurable but a test for the version would be nice.
I know Apple is better than Android keeping devices updated I just dont know how many will install the apps in older iOS versions and it wont work for them. 
(I'm not in the Apple ecosystem/stuff)

According to this "random site": https://david-smith.org/iosversionstats/
iOS 13 is at 92% overall so I guess thats very good. (I wish Android was like this :cry:)

I will accept this PR and release a patch version of this plugin. Ok?

**Comment by LucWollants** [comment]
> I wouldn't say configurable but a test for the version would be nice.

You mean testing the iOS version or the Instagram version (not sure this can be done)?

**Comment by rodrigograca31** [comment]
> > I wouldn't say configurable but a test for the version would be nice.
> 
> You mean testing the iOS version or the Instagram version (not sure this can be done)?

I dont know enoguht iOS to answer but I read that as of iOS 13 that changed so I'd test for the iOS version but from what I know from Android thats not a OS thing, its the instagram app that is registering a "endpoint name" that you can use right?

**Comment by rodrigograca31** [comment]
Ooops I acidentally closed the PR.... now doesnt let me reopen.... says the original repo was deleted....

Can you re open @LucWollants ? sorry.

**Comment by LucWollants** [comment]
> Can you re open
I don't have the rights to do this on this repo. The original PR is from a deleted repo I neither have access rights on.
So best to create a new fork and re-apply the changes and point to this PR.

**Comment by rodrigograca31** [comment]
Ok. I will make a new PR and link to this one to give credits.

but can you answer my previous question? 

was this change (`igo` to `ig` and etc) an iOS 13 change or Instagram one?

**Comment by rodrigograca31** [comment]
Actually seems the answer is here:

https://github.com/vstirbu/InstagramPlugin/pull/106/commits/8988811d617c7ad3a2a8fa1ad7bb8dfe9a685b79 and 
https://github.com/vstirbu/InstagramPlugin/pull/106/commits/4ce60cc3199e1b00bb2a1543994d94b8104b0ba8 and https://github.com/vstirbu/InstagramPlugin/pull/106/commits/b2f66119720b152869ea8aeec764f4100724570f

do you guys agree that I should apply these 3 commits?

**Comment by rodrigograca31** [comment]
Im coming back to this issue now. 

I will manually perform this changes and push to a new branch.

**Pull request closed without merging**
