### PR TITLE
fix: 🐛 fix sharing on iOS #111

### PR DESCRIPTION
**Pull request by rodrigograca31**
More here: https://github.com/vstirbu/InstagramPlugin/pull/112

Credit where credit is due, original code from: @clark-zhao-hs
https://github.com/vstirbu/InstagramPlugin/pull/106

### CODE REVIEW

**Comment by rodrigograca31** [comment]
@LucWollants or @douglaslaiber or @webquali

can someone take a look, maybe run this branch code and let me know if its all good?

then I will commit a version bump and publish to npm

**Comment by rodrigograca31** [comment]
pinging you guys to ask for someone to please review my changes....?

**Comment by drastik** [comment]
@rodrigograca31 I just reviewed today on iPhone 11 pro, iOS 13.4.1 
Instagram is still not available as an option in app list.  

cordova-instagram-ios-issue

**Comment by drastik** [comment]
It does work on iPhone 7, iOS 11.4; however it still pulls the OS app drawer with multiple options (not Instagram exclusive).

**Comment by drastik** [comment]
@rodrigograca31 What are people using for bounties today?  I tried BountySource, but now they're part of this CanYa thing, and their website doesn't even work (can't log in).  

I want to put $150 bounty on making this work on newest iPhones, and also exclusively opening the Instagram app (not OS app drawer)

**Comment by rodrigograca31** [comment]
I also use BountySource and also dont like them and every now and then they are down :sob:
If anyone wants to make a profitable company do a code bounty site!

I've asked GitHub to do it. They have a "marketplace" it would be so easy to make make a button to turn an issue into a bounty that would show up in a marketplace and thousands of developers would see and try to fix it and get paid. It would be the greatest thing for OSS! (Open Source Software)

---

Anyways, back to the main topic.

Did you try it correctly? Its not implemented on the `master` branch yet. Its on a diferente branch.
You need to add the plugin like this:
`ionic cordova plugin add https://github.com/vstirbu/InstagramPlugin#fix-ios-sharing` 
to have this specific changes

Let me know if works.

**Comment by rodrigograca31** [comment]
@drastik any updates!?

**Comment by drastik** [comment]
Sorry, yeah - I had even checked the files after updating the repo the first time, before I commented on this issue.   Yes I updated package to pull from proper branch.  

I am just getting back to this today, going to try a vanilla project to see what it does.

**Comment by rodrigograca31** [comment]
:thinking: Sad to see that this doesnt solve it. 
It should.... but Im not an iOS developer...

**Comment by drastik** [comment]
Haha, me neither.  After 2 yrs on a large project, where along the way seems like every single framework or component we utilized had breaking updates and we had to pivot constantly, it was **only** ever Apple/iOS stuff that caused us the biggest problems and headaches.  Every. Single. Time.  Web always worked, Android always worked, but if you blinked your eyes Apple stopped working.  This is even with automated tests - repeatable any time a plugin or Apple themselves changed something, dozens of issues would spring up, integrations broken, UI components stop working, etc.  

Anyway, /rantover, just saying don't feel bad haha, and I'm not surprised.  I'm still testing this to try and help.

**Comment by drastik** [comment]
@rodrigograca31 Okay, double confirmed it doesn't work.  Also updated an older iPhone 7 to iOS 13.4.x and it affects that one as well as the iPhone 11.

**Comment by rodrigograca31** [comment]
Sucks, sorry I can't help more, I dont even own Apple stuff 😅

Maybe one of you guys can help?
@LucWollants or @douglaslaiber or @webquali
It would be really appreciated!

**Comment by rodrigograca31** [comment]
Merging this because it seems to work.

**Comment by drastik** [comment]
If you look closer at his comment, he is saying it does *not* work. 

:( 
I am also not much help on this one other than testing, nor do I have any desire to code for Crapple.  I want to put a bounty on this if there is a way.

**Comment by rodrigograca31** [comment]
@drastik yeah. I know but thas because it just changed, seems the code was working.

I think you should use https://www.bountysource.com/ to make your bounty and an iOS dev will take care of this once for all.

**Pull request merged**
