### PR TITLE
tweak callbacks

### PR DESCRIPTION
**Pull request by ihadeed**
Hey there

I thought this plugin needs a few changes so it's more like other Cordova plugins out there. Also to make it easier to wrap it in `ionic-native` library. (See https://github.com/driftyco/ionic-native)

The usage after these edits would be like:

```
// successCallback gets invoked without value
// errorCallback gets invoked with error value
shareDataUrl(dataUrl, caption, successCallback, errorCallback);
```

```
// callback gets invoked with values: (isInstalled: boolean, version: string)
isInstalled(callback)
```

### CODE REVIEW

**Comment by vstirbu** [comment]
As this is a breaking change it might be a good idea to clean up the API more.

For example, it is fair to consider that Instagram is not going to accept captions again and just drop that from the API.

Another thing that that might go with this change is the ability to share files by providing a file URL.

Any other changes?

**Comment by micheltobon** [comment]
Instagram Login???? PLEAAAAASSSSEEEE :)

**Comment by vstirbu** [comment]
@ihadeed can you update the PR to 1.x branch, please?

**Comment by ihadeed** [comment]
@vstirbu sure I will update this as soon as I can, sorry for the late response.

**Pull request closed without merging**
